
references:

  build-settings: &build-settings
    machine: true

  no_filters: &no_filters
    filters:
      tags:
        only: /.*/

jobs:
  centos5-devtoolset2-gcc4:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centos5-devtoolset2-gcc4-assets-
      - checkout
      - run:
         name: centos5-devtoolset2-gcc4 build
         command: |
           docker load -i ~/docker/centos5-devtoolset2-gcc4.tar > /dev/null 2>&1 || true
           docker pull centos:5
           make centos5-devtoolset2-gcc4
           mkdir -p ~/docker
           docker save -o ~/docker/centos5-devtoolset2-gcc4.tar dockbuild/centos5-devtoolset2-gcc4:latest dockbuild/centos5:latest
      - run:
         name: centos5-devtoolset2-gcc4 test
         command: |
           make centos5-devtoolset2-gcc4.test
      - save_cache:
          key: centos5-devtoolset2-gcc4-assets-{{ .Revision }}
          paths: ~/docker/centos5-devtoolset2-gcc4.tar
  centos6-devtoolset2-gcc4:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centos6-devtoolset2-gcc4-assets-
      - checkout
      - run:
         name: centos6-devtoolset2-gcc4 build
         command: |
           docker load -i ~/docker/centos6-devtoolset2-gcc4.tar > /dev/null 2>&1 || true
           docker pull centos:6
           make centos6-devtoolset2-gcc4
           mkdir -p ~/docker
           docker save -o ~/docker/centos6-devtoolset2-gcc4.tar dockbuild/centos6-devtoolset2-gcc4:latest dockbuild/centos6:latest
      - run:
         name: centos6-devtoolset2-gcc4 test
         command: |
           make centos6-devtoolset2-gcc4.test
      - save_cache:
          key: centos6-devtoolset2-gcc4-assets-{{ .Revision }}
          paths: ~/docker/centos6-devtoolset2-gcc4.tar
  centos7-devtoolset4-gcc5:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centos7-devtoolset4-gcc5-assets-
      - checkout
      - run:
         name: centos7-devtoolset4-gcc5 build
         command: |
           docker load -i ~/docker/centos7-devtoolset4-gcc5.tar > /dev/null 2>&1 || true
           docker pull centos:7
           make centos7-devtoolset4-gcc5
           mkdir -p ~/docker
           docker save -o ~/docker/centos7-devtoolset4-gcc5.tar dockbuild/centos7-devtoolset4-gcc5:latest dockbuild/centos7:latest
      - run:
         name: centos7-devtoolset4-gcc5 test
         command: |
           make centos7-devtoolset4-gcc5.test
      - save_cache:
          key: centos7-devtoolset4-gcc5-assets-{{ .Revision }}
          paths: ~/docker/centos7-devtoolset4-gcc5.tar
  centos7-devtoolset7-gcc7:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - centos7-devtoolset7-gcc7-assets-
      - checkout
      - run:
          name: centos7-devtoolset7-gcc7 build
          command: |
            docker load -i ~/docker/centos7-devtoolset7-gcc7.tar > /dev/null 2>&1 || true
            docker pull centos:7
            make centos7-devtoolset7-gcc7
            mkdir -p ~/docker
            docker save -o ~/docker/centos7-devtoolset7-gcc7.tar dockbuild/centos7-devtoolset7-gcc7:latest dockbuild/centos7:latest
      - run:
          name: centos7-devtoolset7-gcc7 test
          command: |
            make centos7-devtoolset7-gcc7.test
      - save_cache:
          key: centos7-devtoolset7-gcc7-assets-{{ .Revision }}
          paths: ~/docker/centos7-devtoolset7-gcc7.tar
  ubuntu1004-gcc4:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1004-gcc4-assets-
      - checkout
      - run:
         name: ubuntu1004-gcc4 build
         command: |
           docker load -i ~/docker/ubuntu1004-gcc4.tar > /dev/null 2>&1 || true
           docker pull ubuntu:10.04
           make ubuntu1004-gcc4
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1004-gcc4.tar dockbuild/ubuntu1004-gcc4:latest dockbuild/ubuntu1004:latest
      - run:
         name: ubuntu1004-gcc4 test
         command: |
           make ubuntu1004-gcc4.test
      - save_cache:
          key: ubuntu1004-gcc4-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1004-gcc4.tar
  ubuntu1604-gcc5:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1604-gcc5-assets-
      - checkout
      - run:
         name: ubuntu1604-gcc5 build
         command: |
           docker load -i ~/docker/ubuntu1604-gcc5.tar > /dev/null 2>&1 || true
           docker pull ubuntu:16.04
           make ubuntu1604-gcc5
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1604-gcc5.tar dockbuild/ubuntu1604-gcc5:latest dockbuild/ubuntu1604:latest
      - run:
         name: ubuntu1604-gcc5 test
         command: |
           make ubuntu1604-gcc5.test
      - save_cache:
          key: ubuntu1604-gcc5-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1604-gcc5.tar
  ubuntu1804-gcc7:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1804-gcc7-assets-
      - checkout
      - run:
         name: ubuntu1804-gcc7 build
         command: |
           docker load -i ~/docker/ubuntu1804-gcc7.tar > /dev/null 2>&1 || true
           docker pull ubuntu:18.04
           make ubuntu1804-gcc7
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1804-gcc7.tar dockbuild/ubuntu1804-gcc7:latest dockbuild/ubuntu1804:latest
      - run:
         name: ubuntu1804-gcc7 test
         command: |
           make ubuntu1804-gcc7.test
      - save_cache:
          key: ubuntu1804-gcc7-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1804-gcc7.tar
  ubuntu1904-gcc8:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu1904-gcc8-assets-
      - checkout
      - run:
         name: ubuntu1904-gcc8 build
         command: |
           docker load -i ~/docker/ubuntu1904-gcc8.tar > /dev/null 2>&1 || true
           docker pull ubuntu:19.04
           make ubuntu1904-gcc8
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu1904-gcc8.tar dockbuild/ubuntu1904-gcc8:latest dockbuild/ubuntu1904:latest
      - run:
         name: ubuntu1904-gcc8 test
         command: |
           make ubuntu1904-gcc8.test
      - save_cache:
          key: ubuntu1904-gcc8-assets-{{ .Revision }}
          paths: ~/docker/ubuntu1904-gcc8.tar
  ubuntu2004-gcc9:
    <<: *build-settings
    steps:
      - restore_cache:
          keys:
            - ubuntu2004-gcc9-assets-
      - checkout
      - run:
         name: ubuntu2004-gcc9 build
         command: |
           docker load -i ~/docker/ubuntu2004-gcc9.tar > /dev/null 2>&1 || true
           docker pull ubuntu:19.04
           make ubuntu2004-gcc9
           mkdir -p ~/docker
           docker save -o ~/docker/ubuntu2004-gcc9.tar dockbuild/ubuntu2004-gcc9:latest dockbuild/ubuntu2004:latest
      - run:
         name: ubuntu2004-gcc9 test
         command: |
           make ubuntu2004-gcc9.test
      - save_cache:
          key: ubuntu2004-gcc9-assets-{{ .Revision }}
          paths: ~/docker/ubuntu2004-gcc9.tar
  deploy-master:
    <<: *build-settings
    steps:
      - restore_cache:
          key: centos5-devtoolset2-gcc4-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos5-devtoolset2-gcc4
          command: |
            docker load -i ~/docker/centos5-devtoolset2-gcc4.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/centos5:latest
            docker push dockbuild/centos5-devtoolset2-gcc4:latest
      - restore_cache:
          key: centos6-devtoolset2-gcc4-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos6-devtoolset2-gcc4
          command: |
            docker load -i ~/docker/centos6-devtoolset2-gcc4.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/centos6:latest
            docker push dockbuild/centos6-devtoolset2-gcc4:latest
      - restore_cache:
          key: centos7-devtoolset4-gcc5-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos7-devtoolset4-gcc5
          command: |
            docker load -i ~/docker/centos7-devtoolset4-gcc5.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/centos7:latest
            docker push dockbuild/centos7-devtoolset4-gcc5:latest
      - restore_cache:
          key: centos7-devtoolset7-gcc7-assets-{{ .Revision }}
      - deploy:
          name: Deploy centos7-devtoolset7-gcc7
          command: |
            docker load -i ~/docker/centos7-devtoolset7-gcc7.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/centos7-devtoolset7-gcc7:latest
      - restore_cache:
          key: ubuntu1004-gcc4-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1004-gcc4
          command: |
            docker load -i ~/docker/ubuntu1004-gcc4.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/ubuntu1004:latest
            docker push dockbuild/ubuntu1004-gcc4:latest
      - restore_cache:
          key: ubuntu1604-gcc5-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1604-gcc5
          command: |
            docker load -i ~/docker/ubuntu1604-gcc5.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/ubuntu1604:latest
            docker push dockbuild/ubuntu1604-gcc5:latest
      - restore_cache:
          key: ubuntu1804-gcc7-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1804-gcc7
          command: |
            docker load -i ~/docker/ubuntu1804-gcc7.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/ubuntu1804:latest
            docker push dockbuild/ubuntu1804-gcc7:latest
      - restore_cache:
          key: ubuntu1904-gcc8-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu1904-gcc8
          command: |
            docker load -i ~/docker/ubuntu1904-gcc8.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/ubuntu1904:latest
            docker push dockbuild/ubuntu1904-gcc8:latest
      - restore_cache:
          key: ubuntu2004-gcc9-assets-{{ .Revision }}
      - deploy:
          name: Deploy ubuntu2004-gcc9
          command: |
            docker load -i ~/docker/ubuntu2004-gcc9.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push dockbuild/ubuntu2004:latest
            docker push dockbuild/ubuntu2004-gcc9:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - centos5-devtoolset2-gcc4:
          <<: *no_filters
      - centos6-devtoolset2-gcc4:
          <<: *no_filters
      - centos7-devtoolset4-gcc5:
          <<: *no_filters
      - centos7-devtoolset7-gcc7:
        <<: *no_filters
      - ubuntu1004-gcc4:
          <<: *no_filters
      - ubuntu1604-gcc5:
          <<: *no_filters
      - ubuntu1804-gcc7:
          <<: *no_filters
      - ubuntu1904-gcc8:
          <<: *no_filters
      - ubuntu2004-gcc9:
          <<: *no_filters
      - deploy-master:
          requires:
            - centos5-devtoolset2-gcc4
            - centos6-devtoolset2-gcc4
            - centos7-devtoolset4-gcc5
            - centos7-devtoolset7-gcc7
            - ubuntu1004-gcc4
            - ubuntu1604-gcc5
            - ubuntu1804-gcc7
            - ubuntu1904-gcc8
            - ubuntu2004-gcc9
          filters:
            branches:
              only: master
